# Generated by Django 3.1.1 on 2020-09-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True, verbose_name='USER_ID')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('brand', models.CharField(blank=True, max_length=255, null=True, verbose_name='Бренд')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('status', models.IntegerField(blank=True, null=True, verbose_name='Статус')),
                ('status_vikup', models.IntegerField(blank=True, null=True, verbose_name='Уведомление по выкупу [0-нет, 1-да]')),
                ('status_dostavka', models.IntegerField(blank=True, null=True, verbose_name='Уведомление доставке [0-нет, 1-да]')),
                ('description', models.TextField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('size', models.CharField(blank=True, max_length=255, null=True, verbose_name='Размер')),
                ('price_dollar', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Стоимость в валюте')),
                ('kurs', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Курс выкупа')),
                ('price_vikup', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Cтоимость выкупа')),
                ('koef_vikup', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Коэффициент выкупа')),
                ('price_vikup_client', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Cтоимость выкупа для клиента')),
                ('dohod_vikup', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Доход по выкупу')),
                ('ves', models.IntegerField(blank=True, null=True, verbose_name='Вес товара(г)')),
                ('price_dostavki_za_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Стоимость доставки за 1кг (1000г)')),
                ('price_dostavki', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Cебестоимость доставки')),
                ('koef_dostavka', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Коэффициент доставка')),
                ('price_dostavki_klienty', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Cтоимость доставки для клиента')),
                ('dohod_dostavka', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Доход по доставке')),
            ],
        ),
    ]
